---
- name: Test to see if nodes already joined to cluster
  ansible.builtin.command: ls /etc/kubernetes
  changed_when: false
  register: kubedirtest
  failed_when: kubedirtest.rc > 2
  tags: kubedirtest

- name: Generate join token
  ansible.builtin.command: kubeadm token create --print-join-command
  changed_when: false
  register: kubeadm_join_cmd
  delegate_to: "{{ groups.k8s_master[0] }}"
  run_once: true

- name: Set kubeadm_join variable content
  ansible.builtin.set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"
  changed_when: false

- name: Run kubeadm join
  ansible.builtin.command: "{{ kubeadm_join }}"
  when: "'pki' not in kubedirtest.stdout"
  changed_when: true
  tags: kubedirtest
